# Generated by Django 5.1.2 on 2024-11-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='admissions',
            field=models.CharField(default='DIP/PL/2019033', max_length=22),
        ),
    ]
