# Generated by Django 5.1.2 on 2024-11-12 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_admissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, upload_to='customers_images/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='admissions',
            field=models.CharField(max_length=22, validators=[django.core.validators.RegexValidator(code='invalid_admission', message='Admission must be in the format DIP/PL/XXXXXXX (7 digits).', regex='^DIP/PL/\\d{7}$')]),
        ),
    ]
